INSERT INTO tb_user (name, email, password) VALUES ('Alex Green', 'alex@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Bob Brown', 'bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Maria Purple', 'maria@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');

INSERT INTO tb_role (authority) VALUES ('ROLE_MEMBER');
INSERT INTO tb_role (authority) VALUES ('ROLE_VISITOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_ADMIN');

INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES (3, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (3, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES (3, 3);

INSERT INTO tb_genre (name) VALUES ('Animação');
INSERT INTO tb_genre (name) VALUES ('Terror');
INSERT INTO tb_genre (name) VALUES ('Aventura');

INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Bob Esponja: O Incrível Resgate', 'Eles já não estão na Fenda do Biquini', 2020, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/wu1uilmhM4TdluKi2ytfz8gidHf.jpg', 'Onde está Gary? Segundo Bob Esponja, Gary foi caracolstrado pelo temível Rei Poseidon e levado para a cidade perdida de Atlantic City. Junto a Patrick Estrela, ele sai em uma missão de resgate ao querido amigo, e nesta jornada os dois vão conhecer novos personagens e viver inimagináveis aventuras.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Era Uma Vez um Boneco de Neve', 'Tudo começou com um pouco de magia.', 2020, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/gQXuRa5TK7fALJObMvmScxCck6J.jpg', 'Os primeiros passos de Olaf conforme ele ganha vida e busca sua identidade nas montanhas nevadas dos arredores de Arendelle.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('A Caminho da Lua', 'Believing is Everything', 2020, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/htBUhLSS7FfHtydgYxUWjL3J1Q1.jpg', 'Uma garota constrói uma nave espacial e parte rumo ao espaço à procura da deusa da lua.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Colheita Maldita', 'Em seu mundo, os adultos não podem... viver.', 1984, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/49jjiMwuWcucb2T01OAkP4ZNubG.jpg', 'A viagem de um médico com sua mulher é interrompida quando o casal encontra o corpo de um garoto na estrada. Eles tentam chamar a polícia e acabam em um vilarejo onde jovens adoradores de um culto macabro realizam sacrifícios humanos.', 2);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Dead Rising', 'Endgame', 2016, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/oDvkt6sbGBLXt6EfPgl5ozoIb2f.jpg', 'Chase Carter, um jornalista investigativo assombrado por seu passado e agora perseguido pelos militares. Depois de escapar por pouco de uma quarentena zumbi, Chase não consegue se livrar do remorso de ter deixado um colega de confiança para trás. Agora, quando volta para a zona de quarentena para expor os arquitetos da epidemia, vai descobrir um segredo ainda pior do que poderia ter imaginado.', 2);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('O Iluminado', 'Ele veio como zelador, mas este hotel tinha seus próprios guardiões, que estavam lá há muito tempo.', 1980, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/mmd1HnuvAzFc4iuVJcnBrhDNEKr.jpg', 'Durante o inverno, um homem é contratado para ficar como vigia em um hotel no Colorado e vai para lá com a mulher e seu filho. Porém, o contínuo isolamento começa a lhe causar sérios problemas mentais e ele vai se tornado cada vez mais agressivo e perigoso, ao mesmo tempo que seu filho passa a ter visões de acontecimentos ocorridos no passado, que também foram causados pelo isolamento excessivo.', 2);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Piratas do Caribe: O Baú da Morte', 'Jack está de volta.', 2006, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/iv5ilhzGL2BXu64HRNcFox3447g.jpg', 'Will e Elizabeth estão prestes a se casar quando o lendário pirata Davy Jones, comandante do invencível navio assombrado, aparece para cobrar uma dívida do capitão Jack Sparrow, amigo do casal. A única chance de Sparrow se livrar de uma maldição de Jones é encontrando o baú da morte.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Avatar', 'Descubra um novo mundo.', 2009, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/bIL7ENqh1egWTxN41sM2W42JqPc.jpg', 'Apesar de não ter mais os movimentos da perna, o ex-fuzileiro naval Jake Sully ainda sente que pode ser um guerreiro. Sua intuição começa a se tornar realidade quando ele viaja anos-luz até a estação espacial montada no Planeta Pandora. Habitado por grandes seres azuis, os Na´vi, o local tem uma atmosfera fatal para qualquer terrestre. Por isso, oficiais criaram o programa Avatar, em que um corpo biológico, híbrido de humano e Na´vi, pode ser comandado a distância.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Homem de Ferro', 'Heróis não nascem. Eles são construídos.', 2008, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/A1m5BJznmmsDyj25AnhDyFbBSJJ.jpg', 'Tony Stark (Robert Downey Jr.) é um industrial bilionário, que também é um brilhante inventor. Ao ser sequestrado ele é obrigado por terroristas a construir uma arma devastadora mas, ao invés disto, constrói uma armadura de alta tecnologia que permite que fuja de seu cativeiro. A partir de então ele passa a usá-la para combater o crime, sob o alter-ego do Homem de Ferro.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Jumanji: Próxima Fase', 'O jogo bugou.', 2019, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/oLma4sWjqlXVr0E3jpaXQCytuG9.jpg', 'Tentado em revisitar o mundo de Jumanji, Spencer (Alex Wolff) decide consertar o jogo de videogame que permite que os jogadores sejam transportados ao local. Logo o quarteto formado por Smolder Bravestone (Dwayne Johnson), Moose Finbar (Kevin Hart), Shelly Oberon (Jack Black) e Ruby Roundhouse (Karen Gillan) ressurge, agora comandado por outras pessoas: os avôs de Spencer e Fridge (Danny DeVito e Danny Glover) assumem as personas de Bravestone e Finbar, enquanto o próprio Fridge (Ser´Darius Blain) agora está sob a pele de Oberon.', 3);

INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Este é um clássico de terror indispensável, que conta como um ex-professor se muda com a sua esposa e filho para um hotel de luxo nas montanhas, onde irá trabalhar como zelador nos meses de Inverno, em que o hotel fica fechado e isolado pela neve. O que ele não sabia é que o lugar, onde já aconteceram dezenas de mortes, é um lugar maléfico e assombrado. É baseado num romance de Stephen King e é o meu filme favorito de Stanley Kubrick. Embora contenha cenas muito violentas de carnificina e nudez, é relativamente calmo e pudico em comparação a outros filmes do género. Desde o início, consegue criar um agradável suspense em torno de John Torrence e da sua família, sem nunca especificar duas coisas distintas: a natureza do dom intuitivo do filho de John e a natureza do mal que vive no hotel. São coisas propositadamente deixadas em aberto, talvez para aumentar o impacto do final. Jack Nicholson interpretou a personagem principal e acho justo reconhecer que foi o papel mais desafiador e mais icónico da sua carreira. Ele foi fantástico, o seu corpo e expressão facial ajudaram imensamente a torná-lo mais realista e aterrador. A mesma coisa pode ser dita de Shelley Duvall, excelente como Sra. Torrence, capaz de harmonizar sentimentos de descrença, medo, impotência e urgência para agir.', 1, 6);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('O filme tem bons efeitos especiais e visuais, bem como um conjunto de cenários e ambientes excelente e credível.', 1, 6);